spring:
  application:
    name: search-service
  mvc:
    path match:
      matching-strategy: ant_path_matcher


server:
  port: 8090
  servlet:
    context-path: /search-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://174.129.84.80:8761/eureka

logging:
  level:
    com.hilltop: ${LOG_LEVEL:DEBUG}
  file:
    path: ${LOG-PATH:/home/ubuntu/log}
